linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/gotd/tl
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - exitAfterDefer
      - whyNoLint
      - singleCaseSwitch

linters:
  disable-all: true
  enable:
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gochecknoglobals
    - gocognit

  # Do not enable:
  # - wsl       (too opinionated about newlines)
  # - godox     (todos are OK)
  # - bodyclose (false positives on helper functions)
  # - prealloc  (not worth it in scope of this project)
  # - maligned  (same as prealloc)
  # - funlen    (gocyclo is enough)

issues:
  exclude-rules:
    # TODO(ernado): Should we refactor Parse() functions?
    - linters: [gocyclo, gocognit]
      text: "Parse"

    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll
        - gochecknoglobals
    # Ignore shadowing of err.
    - linters: [govet]
      text: 'declaration of "err"'
    # Ignore linters in main packages.
    - path: main\.go
      linters: [gochecknoglobals, goconst, funlen, gocognit, gocyclo]
